DOXYFILE = 'Doxyfile-mcss'
FAVICON = 'doxygen/favicon/favicon.ico'
MAIN_PROJECT_URL = 'http://developers.pages.uav.radar-mms.com/v2/libs/essentials/rolly/'
VERSION_LABELS = True
FINE_PRINT = """<p>Rolly handbook is part of the <a href="http://gitlab.uav.radar-mms.com/developers/v2/libs/essentials/rolly/">Rolly project</a>, copyright © <a href="https://github.com/whs31">Dmitriy Riazantsev</a>, 2023&ndash;2024.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>.</p>"""
LINKS_NAVBAR1 = [
  ("Handbook", 'pages', []),
  ("Modules", 'modules', []),
  ("Namespaces", 'namespaces', [])
]
