name: Build (Ubuntu, GCC-10)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, c++20]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check GCC version
      run: |
            gcc --version
            g++ --version

    - name: Run tests
      run:  |
            rm -rf build
            conan build . -b "missing" -o "rolly/*:test=True"
            ./build/${{env.BUILD_TYPE}}/tests/rolly-test --reporter JUnit::out=test_detail.xml --reporter console::out=-::colour-mode=ansi

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() 
      with:
        report_paths: 'test_detail.xml'
        comment: true

    - name: Create package
      run:  |
            rm -rf build
            conan create . -b "missing" --user="whs31" --channel="dev"
            conan upload "rolly" -r "home" -c
    
