name: Build (Ubuntu, GCC-13)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, c++20]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Create package
      run:  |
            rm -rf build
            conan create . -b "missing" --user="whs31" --channel="dev"
            conan upload "rolly" -r "home" -c --only-recipe
    
