name: Test (Ubuntu, GCC-13)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  checks: write
  pull-requests: write

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: [self-hosted, c++20]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run tests
      run:  |
            rm -rf build
            conan build . -b "missing" -o "rolly/*:test=True"
            ./build/${{env.BUILD_TYPE}}/tests/rolly-test --reporter JUnit::out=test_detail.xml --reporter console::out=-::colour-mode=ansi

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() 
      with:
        report_paths: 'test_detail.xml'
        comment: true
